services:
  # frontend:
  #   image: fe-financial-tracker
  #   ports:
  #     - "127.0.0.1:8080:8080"
  
  backend:
    image: be-financial-tracker
    ports:
      - "127.0.0.1:8081:8080"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - database
    command: npm run start

  database:
    image: postgres
    ports:
      - "127.0.0.1:8082:5432"
    volumes:
      - ./database:/var/lib/postgresql/data:r+w
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      